DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS entity_attributes;
DROP TABLE IF EXISTS entities;
DROP TABLE IF EXISTS attributes;
DROP TABLE IF EXISTS otp_codes;
DROP TABLE IF EXISTS otp_blacklist;

