definitions:
  dto.UserSignUpInput:
    properties:
      password:
        type: string
      passwordVerification:
        type: string
      phoneNumber:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/sign-up:
    post:
      consumes:
      - application/json
      description: create user account
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.UserSignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
        default:
          description: ok
          schema:
            type: string
      summary: User SignUp
      tags:
      - users-auth
swagger: "2.0"
